name: Food102
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - opencv
  - tqdm
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - autodistill
      - autodistill-clip
      - autodistill-detic
      - autodistill-yolov8
      - autodistill_grounding_dino
      - autodistill-grounded-sam
      - roboflow
      - ultralytics
      - torch==2.3.0+cu121